import Footer from "@/components/footer";
import Header from "@/components/header";
import Hero from "@/components/hero";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="scroll-smooth scroll-p-14 md:scroll-p-12 lg:scroll-pt-8"
    >
      <body className="max-w-screen-xl mx-auto">
        {children}
        <Footer />
      </body>
    </html>
  );
}
